# ██████╗░██╗░░░░░██╗░░░██╗░██████╗░██╗███╗░░██╗██████╗░██╗░░░░░░█████╗░███╗░░██╗██╗░░██╗
# ██╔══██╗██║░░░░░██║░░░██║██╔════╝░██║████╗░██║██╔══██╗██║░░░░░██╔══██╗████╗░██║██║░██╔╝
# ██████╔╝██║░░░░░██║░░░██║██║░░██╗░██║██╔██╗██║██████╦╝██║░░░░░███████║██╔██╗██║█████═╝░
# ██╔═══╝░██║░░░░░██║░░░██║██║░░╚██╗██║██║╚████║██╔══██╗██║░░░░░██╔══██║██║╚████║██╔═██╗░
# ██║░░░░░███████╗╚██████╔╝╚██████╔╝██║██║░╚███║██████╦╝███████╗██║░░██║██║░╚███║██║░╚██╗
# ╚═╝░░░░░╚══════╝░╚═════╝░░╚═════╝░╚═╝╚═╝░░╚══╝╚═════╝░╚══════╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝

# Developer / Разработчик: ILeZzoV

# Socials / Ссылки:
# • Contact with me / Связаться: https://t.me/ilezovofficial
# • Telegram Channel / Телеграм канал: https://t.me/ilezzov
# • GitHub: https://github.com/ilezzov-code

# Plugin Pages / Страницы плагинов:
# • Modrinth:
# • Spigot:
# • CurseForge:
# • Hangar:

# By me coffee / Поддержать разработчика:
# • DA: https://www.donationalerts.com/r/ilezzov_dev
# • YooMoney: https://yoomoney.ru/fundraise/193CD8F13OH.250319
# • Telegram Gift: https://t.me/ilezovofficial
# • TON: UQCInXoHOJAlMpZ-8GIHqv1k0dg2E4pglKAIxOf3ia5xHmKV
# • BTC: 1KCM1QN9TNYRevvQD63UF81oBRSK67vCon
# • Card: 5536914188326494

# Supporting messages languages / Доступные языки сообщений:
# • Русский (ru-RU)
# •  English (en-US)
language: "ru-RU"

# Check the plugin for updates
# Проверять плагин на наличие обновлений
check_updates: true


# Don't edit this
# Не редактируйте это
config_version: 1.0




