Urls:
  url-to-file-version: "https://raw.githubusercontent.com/ilezzov-code/PluginBlank/main/VERSION"
  url-to-download-latest-version: "https://github.com/ilezzov-code/PluginBlank/releases"

Bstats:
  enable: true
  plugin-id: 25280

Messages:
  create-new-file: "The file &6%s &rhas been created"
  add-new-keys-to-file: "The file &6%s &rhas been updated. Check then new settings"
  legacy-plugin-version: "You use &coutdated &rplugin version: &6%s&r. \nPlease, download latest plugin version: &6%s&r. \nDownload — &6%s"
  latest-plugin-version: "You use &alatest &rplugin version: &6%s"
  has-error: "An error occurred: &c%s"
  success-connect-to-database: "Connection to the database is &aestablished"
  plugin-enable: "Plugin has been &aenabled \n&rDeveloper: &6%s \n&rVersion: &6%s \n&rWebsite: &6%s"
  plugin-disable: "Plugin has been &cdisabled \n&rDeveloper: &6%s \n&rVersion: &6%s \n&rWebsite: &6%s"

